using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuarryManagementSystem.Models.Domain
{
    public class JournalEntry
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Entry Number")]
        public string EntryNumber { get; set; } = string.Empty;

        [Required]
        [Display(Name = "Entry Date")]
        [DataType(DataType.Date)]
        public DateTime EntryDate { get; set; }

        [StringLength(100)]
        [Display(Name = "Reference")]
        public string? Reference { get; set; }

        [StringLength(500)]
        [Display(Name = "Description")]
        public string? Description { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        [Display(Name = "Total Debit")]
        public decimal TotalDebit { get; set; } = 0;

        [Column(TypeName = "decimal(18,2)")]
        [Display(Name = "Total Credit")]
        public decimal TotalCredit { get; set; } = 0;

        [StringLength(450)]
        [Display(Name = "Posted By")]
        public string? PostedBy { get; set; }

        [Display(Name = "Auto Generated")]
        public bool IsAutoGenerated { get; set; } = false;

        [Display(Name = "Created Date")]
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        // Navigation properties
        public virtual ICollection<JournalEntryLine> JournalEntryLines { get; set; } = new List<JournalEntryLine>();
        public virtual ApplicationUser? PostedByUser { get; set; }

        // Helper methods
        public bool IsBalanced()
        {
            return TotalDebit == TotalCredit;
        }

        public bool IsPosted()
        {
            return !string.IsNullOrEmpty(PostedBy);
        }

        public bool CanEdit()
        {
            return !IsPosted();
        }

        public string GetStatus()
        {
            if (IsPosted())
                return "Posted";
            return "Draft";
        }

        public decimal GetDifference()
        {
            return Math.Abs(TotalDebit - TotalCredit);
        }

        public void RecalculateTotals()
        {
            TotalDebit = JournalEntryLines.Sum(line => line.DebitAmount);
            TotalCredit = JournalEntryLines.Sum(line => line.CreditAmount);
        }

        public bool ValidateEntry()
        {
            // Check if debits equal credits
            if (!IsBalanced())
                return false;

            // Check if there are entry lines
            if (JournalEntryLines.Count == 0)
                return false;

            // Check if all lines have valid amounts
            foreach (var line in JournalEntryLines)
            {
                if (line.DebitAmount < 0 || line.CreditAmount < 0)
                    return false;
                if (line.DebitAmount > 0 && line.CreditAmount > 0)
                    return false; // Cannot have both debit and credit
            }

            return true;
        }

        // Common journal entry types for quarry operations
        public static readonly Dictionary<string, string> EntryTypes = new()
        {
            { "SALE", "Sales Transaction" },
            { "PURCHASE", "Purchase Transaction" },
            { "PAYMENT", "Payment Transaction" },
            { "RECEIPT", "Receipt Transaction" },
            { "PAYROLL", "Payroll Transaction" },
            { "ADJUSTMENT", "Adjustment Entry" },
            { "DEPRECIATION", "Depreciation Entry" },
            { "ACCRUAL", "Accrual Entry" }
        };

        // Generate entry number
        public static string GenerateEntryNumber(string prefix = "JE")
        {
            return $"{prefix}/{DateTime.Now:yyyyMMdd}/{Guid.NewGuid().ToString().Substring(0, 6).ToUpper()}";
        }
    }
}